### PR TITLE
These changes make the tests pass again.

### PR DESCRIPTION
**Pull request by mhaupt**
This is a git noob pull request. I wish to exclude 2abbba5 from the request. Or make me a contributor, so that I can work on branches. :-)

### CODE REVIEW

**Comment by smarr** [comment]
Great to see :)

Before we go into the technical things, let's talk a bit about how we want to do this. I assume you haven't worked much with github before.

I think it might make sense to work on the [SOM-st](https://github.com/SOM-st) organization repo. I just added you to the corresponding organization.

So, I would propose to move the PR to https://github.com/SOM-st/som-java

Then, the question is to work on personal or the main repos for changes. And, I don't have a strong preference. But, I think, it would be nice to use pull requests to group and discuss changes.

The GitHub integration is very nice. Once you submitted some branch as a PR, you can completely change everything on that branch, which includes rebasing on latests master, removing commits, completely rewriting commit history to remove unimportant intermediate mistakes/bugs, etc. Github essentially connects a PR with the branch name, so even force-pushing to a branch works. The PR is then nicely updated and conversation can continue.

Since you mentioned you want to drop 2abbba5, I love `git rebase -i $SOME_HASH`.
In your specific case, let's pick 32151ed1a9068712a53523b08510eccfc2f70117 as one of the earlier commits as a basis: `git rebase -i 32151ed1a9068712a53523b08510eccfc2f70117`.

This should give you a list of your commits in a text editor, perhaps vim.
They have a keyword `pick` before them. This text file essentially instructs git what to do with each commit. I like to `squash`, `drop`, `fixup`, or `edit` commits from time to time with that.
I mostly use `fixup` and `squash`, in your case, `drop` is probably what you want to do.
With `fixup`, the commit id mentioned following it will just be combine with the previous one, ignoring the commit message. That's nice for fixing intermediate bugs.
`squash` is something I use to fold separate commits into one were I want to keep part of the commit message of the second commit. I usually do that to cleanup history. I think history is meant for the code reader to understand the motivation/context of changes, and not as a log of fine-grained actions.

Hope this helps :)

**Comment by mhaupt** [comment]
Thanks. I do have some (basic) experience with Github, and appreciate your intro.

Moving the PR: is this done by simply submitting it there, or is the move supported as a separate operation? (I looked around but could not find something that looked like it.)

As for rebasing, why are you suggesting 32151ed, when 07c3fee is more recent and just before the change I applied and want to keep out?

**Comment by smarr** [comment]
Yeah, don't think there is a real 'move' operation. So, resubmission would be one way, or, we just do it here, and then use SOM-st in the future.

I was suggesting the older one, because I don't know how drop works if you drop the first commit. So, just playing it safe :)

**Comment by mhaupt** [comment]
Well, that rebase didn't help. Now I had to pull and tadaa, there's a merge that re-introduces the change I wanted to keep out.

**Comment by mhaupt** [comment]
I'll start over with a pull request on the SOM-st repo.

**Pull request closed without merging**
